### ISSUE TITLE
Support for golang context

### ISSUE THREAD

**Issue by rShetty** [gojektech/heimdall#17]
- Support for golang context across both http and hystrix clients 
Something on these lines:
`https://godoc.org/golang.org/x/net/context/ctxhttp`

**Comment by shubham7saxena** [comment]
I'll take up this one.

**Comment by shubham7saxena** [comment]
@rShetty this is a nice feature to have. I am just a little sceptic in the sense that it will require a change in interface and not everyone might want to use the context. what do you think?

**Comment by shubham7saxena** [comment]
in case, it's ok. please mark it in dev. I have started work on it.

**Comment by rShetty** [comment]
@shubham7saxena Can we create a separate interface with implementations accepting context ? Thinking to not break current interfaces

**Comment by shubham7saxena** [comment]
https://github.com/gojektech/heimdall/pull/28

**Comment by spy16** [comment]
@rShetty Why not use `req.WithContext(ctx context.Context)` method on `http.Request` object instead of a new client altogether ? This is how `http.Client` does it. Since `httpclient.Client` type is using `http.Client`, using `req.WithContext` would already work without any changes.. That way, no need of introducing new client type. It will still act as a drop-in replacement for standard http client. 

So, if context cancellation is not needed, using `client.Get("http://google.com",...)` will be enough. In case context cancellation is needed:

```go
req, err := http.NewRequest("GET", "http://google.com", nil)
if err != nil {
    return err
}
req = req.WithContext(context.Background())

resp, err := client.Do(req)
```

**Comment by rShetty** [comment]
@spy16 Yes, to be compatible with the `http.Client` we will go ahead with not doing this. Closing this
